// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC8vEGf7x_d1drZ_QiguTEGy9p2iSh1Gc',
    appId: '1:415092375128:web:d6a0cc6a5891b435e3942d',
    messagingSenderId: '415092375128',
    projectId: 'my-project-090524',
    authDomain: 'my-project-090524.firebaseapp.com',
    storageBucket: 'my-project-090524.appspot.com',
    measurementId: 'G-MHKMEV826T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkq0_2GrbFXB202jQbAKOJVSWt-l8Paro',
    appId: '1:415092375128:android:f03e89c259a204c5e3942d',
    messagingSenderId: '415092375128',
    projectId: 'my-project-090524',
    storageBucket: 'my-project-090524.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiytzr6YoP7iODZ1juIaa1gOGMpgZszts',
    appId: '1:415092375128:ios:7d02e2bf60b868dee3942d',
    messagingSenderId: '415092375128',
    projectId: 'my-project-090524',
    storageBucket: 'my-project-090524.appspot.com',
    iosBundleId: 'com.example.httpApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiytzr6YoP7iODZ1juIaa1gOGMpgZszts',
    appId: '1:415092375128:ios:7d02e2bf60b868dee3942d',
    messagingSenderId: '415092375128',
    projectId: 'my-project-090524',
    storageBucket: 'my-project-090524.appspot.com',
    iosBundleId: 'com.example.httpApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC8vEGf7x_d1drZ_QiguTEGy9p2iSh1Gc',
    appId: '1:415092375128:web:10dd11bdaf8f12c8e3942d',
    messagingSenderId: '415092375128',
    projectId: 'my-project-090524',
    authDomain: 'my-project-090524.firebaseapp.com',
    storageBucket: 'my-project-090524.appspot.com',
    measurementId: 'G-6RQ5XCJPBW',
  );

}